export enum VerificationPurpose {
    EMAIL = 'EMAIL',
    PASSWORD_RESET = 'PASSWORD_RESET',
    ACCOUNT_ACTIVATION = 'ACCOUNT_ACTIVATION',
    ACCOUNT_VERIFICATION = 'ACCOUNT_VERIFICATION',
    PASSWORD_CHANGE = 'PASSWORD_CHANGE',
    USER_REGISTRATION = 'USER_REGISTRATION',
    USER_LOGIN = 'USER_LOGIN',
    USER_DELETION = 'USER_DELETION',
    USER_UPDATE = 'USER_UPDATE'
}
